spring:
  main:
    banner-mode: console

  datasource:
    url: ${datasource.url} bank_app?createDatabaseIfNotExist=true
    username: root
    password: Elina1980.

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        logging.level.org.springframework.web: DEBUG
        logging.level.org.hibernate.SQL: DEBUG
        logging.level.org.hibernate.type: TRACE
      properties:
        hibernate:
          SQL: INFO
          type:
            INFO

  liquibase:
    change-log: classpath:db.changelog/changelog-master.yaml
    enabled: true
    drop-first: true


server:
  port: 8080








