spring:
  main:
    banner-mode: console
    allow-circular-references: true


  datasource:
    url: ${datasource.url}bank_app?createDatabaseIfNotExist=true
    username: root
    password: Elina1980.

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        logging.level.org.springframework.web: DEBUG
        logging.level.org.springframework.web.client: DEBUG
        logging.level.org.springframework: DEBUG
        logging.level.org.hibernate.SQL: DEBUG
        logging.level.org.hibernate.type: DEBUG

        logging.level.root: DEBUG
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      properties:
        hibernate:
          SQL: INFO
          type:
            INFO

  liquibase:
    change-log: classpath:db.changelog/changelog-master.yaml
    enabled: true
    drop-first: true




#  security:
#    filter:
#      order:  10
#  security:
#    user:
#     password: Test12345_




server:
  port: 8080
#
#admin:
#  username: root
#  password: root










